### ISSUE TITLE
Validate the labels before execution

### ISSUE THREAD

**Issue by AuHau** [Financial-Times/github-label-sync#135]
I had non-valid color specified in my YAML and your tool executed without any validation which resulted in partly executed synchronization as GitHub rejected to accept the label with the invalid color and thrown error:

```
GitHub Error:
PATCH /repos/ethersphere/bee-js/labels/help%20wanted
422: Validation Failed
```

**Comment by JakeChampion** [comment]
@AuHau can you give an example of how to reproduce this error please?

**Comment by AuHau** [comment]
Hmmm, I originally thought that it stopped the syncing for the remaining items, but it seems that the remaining items finished so in the end I guess it is not such a biggie. Also, when I re-run the tool it picks up stuff that is unsynced so again I guess not such a biggie.

For example, syncing this YAML should fail:
```yaml
- name: dif:trivial
  color: 'some invalid color'
  aliases: []
  description: Can be confidently tackled by newcomers
```

**Comment by Chaphasilor** [comment]
Had this issue today as well. My colors were invalid (I included the `#`), but the dry run didn't report any errors :)

**Comment by shoichiaizawa** [comment]
I also happened to encounter this error when a colour value was a hex value not containing a-f.

e.g.

```yaml
# File: labels.yaml

# [...]

- name: "type: test"
  color: 257759  # <= this causes an error without `""` because it seems to be considered as a number
  description: Adding missing tests or correcting existing tests (jest, storybook, cypress)
  aliases:
    - test
    - testing

# [...]
```

```console
❯❯ github-label-sync -a $HOMEBREW_GITHUB_API_TOKEN -l labels.yaml shoichiaizawa/labels
Syncing labels for "shoichiaizawa/labels"
Fetching labels from GitHub
 > Missing: the "type: test" label is missing from the repo. It will be created.
Applying label changes, please wait…
GitHub Error:
POST /repos/shoichiaizawa/labels/labels
422: Invalid request.

For 'properties/color', 257759 is not a string.
```

**Comment by shoichiaizawa** [comment]
This is another instance of the validation failure when the `description` has more than 100 characters. Even filling the `description` field via the GUI, 100 characters seem to be the upper limit.


```yaml
# File: labels.yaml

# [...]

- name: "type: test"
  color: "257759"
  description: Adding missing tests or correcting existing tests (jest, storybook, cypress) foo bar baz qux quux quuz corge  # <== description can be no more than 100 characters, otherwise, an error occurs
  aliases:
    - test
    - testing

# [...]
```

```console
❯❯ github-label-sync -a $GITHUB_API_TOKEN -l labels.yaml shoichiaizawa/labels
Syncing labels for "shoichiaizawa/labels"
Fetching labels from GitHub
 > Changed: the "type: test" label in the repo is out of date. It will be updated to "type: test" with color "#257759" and description "Adding missing tests or correcting existing tests (jest, storybook, cypress) foo bar baz qux quux quuz corge".
Applying label changes, please wait…
GitHub Error:
PATCH /repos/shoichiaizawa/labels/labels/type%3A%20test
422: Validation Failed
```

**Comment by shoichiaizawa** [comment]
Also, when the colour hex value is applied as `2e7733`, it is considered as a `number`.
(i.e. In JavaScript, this `2e7733` is considered `Infinity`; hence is it considered `number`.)

```yaml
# File: labels.yaml

# [...]

- name: 'status: PR welcome'
  # The value `2e7733` is considered as a `number` without single or double quotes
  color: 2e7733
  description: Welcome to pull request
  aliases:
    - 'status: ready for PR'

# [...]
```

```console

❯❯ github-label-sync -a $GITHUB_API_TOKEN -l labels.yaml shoichiaizawa/labels
Syncing labels for "shoichiaizawa/labels"
Fetching labels from GitHub
 > Changed: the "status: PR welcome" label in the repo is out of date. It will be updated to "status: PR welcome" with color "#Infinity" and description "Welcome to pull request".
Applying label changes, please wait…
GitHub Error:
PATCH /repos/shoichiaizawa/labels/labels/status%3A%20PR%20welcome
422: Invalid request.

For 'properties/color', nil is not a string.
```
