### ISSUE TITLE
Add more validations to labels name and description

### ISSUE THREAD

**Issue by srealmoreno** [Financial-Times/github-label-sync#171]
## What

The Github api has some validations besides character length.

- Label Name:
     
     1. Must contain more than native emojis

        When using a name that only contains emojis, this error occurs:
        ![image](https://user-images.githubusercontent.com/50985135/173261112-35f5a076-42dd-4f67-b3da-74e700911b8f.png)

- Description:

    2. 4-byte characters are not allowed
  
        ![image](https://user-images.githubusercontent.com/50985135/173261060-76422365-94d1-4827-975a-c7e5a2e055a5.png)

## Details
my `labels.yml`

```yaml
- name: 😀 😃 😄 😁
  color: "536266"
  description: This is a name only contains emojis

- name: bug 🐞
  color: d73a4a
  description: 
    This is a description that contains emojis 4-byte unicode 🐞
```

With that file, the script will fail with the following message:

```plain
GitHub Error:
POST /repos/srealmoreno/test-label-sync/labels
422: Validation Failed
```
It would be great if you showed the error with `--dry-run` option.

Similar issues #42 #135
